on: [push]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
        - name: Repository git verification
          uses: actions/checkout@v2

        - name: Node version Install
          uses: actions/setup-node@v1
          with:
            node-version: 14


        - name: Dependency install
          run: npm install

        - name: Lint execution
          run: npm run lint
